# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Creating .env

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create:
 
    runs-on: ubuntu-18.04
 
    steps:
    - name: Make .env File
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
        envkey_BASE_URL: ${{ secrets.BASEU_URL }}
